-- NisaanSearchEngine V1 database schema
-- PostgreSQL / Supabase compatible

create extension if not exists pgcrypto;

create table if not exists pages (
    id bigint generated by default as identity primary key,
    url text not null unique,
    canonical_url text,
    domain text not null,
    title text,
    description text,
    content text,
    language text,
    status_code integer,
    content_hash text,
    word_count integer default 0,
    crawled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists pages_domain_idx on pages(domain);
create index if not exists pages_crawled_at_idx on pages(crawled_at desc);
create index if not exists pages_content_hash_idx on pages(content_hash);

create table if not exists crawl_queue (
    id bigint generated by default as identity primary key,
    url text not null unique,
    source_url text,
    depth integer not null default 0,
    status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed', 'blocked')),
    attempts integer not null default 0,
    next_attempt_at timestamptz not null default now(),
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists crawl_queue_pending_idx
    on crawl_queue(status, next_attempt_at)
    where status = 'pending';

create table if not exists crawl_runs (
    id uuid primary key default gen_random_uuid(),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    pages_discovered integer not null default 0,
    pages_crawled integer not null default 0,
    pages_failed integer not null default 0,
    status text not null default 'running' check (status in ('running', 'completed', 'failed')),
    error_message text
);

create table if not exists crawl_seeds (
    id bigint generated by default as identity primary key,
    url text not null unique,
    enabled boolean not null default true,
    max_depth integer not null default 2,
    created_at timestamptz not null default now()
);

-- Keep the API/search layer independent from the crawler.
comment on table pages is 'Normalized crawled web documents used as the source of truth for the search index.';
comment on table crawl_queue is 'URL frontier for controlled crawling.';
comment on table crawl_runs is 'Crawler execution metrics and status.';
comment on table crawl_seeds is 'Approved starting URLs for crawling.';
